# Build and publish a release of InputPlumber using semantic-release whenever
# changes are merged into main.
name: "🎉 Release"

permissions:
  contents: write

on:
  push:
    branches:
      - main
      - v0.x
      - v1.x
    paths-ignore:
      - README.md
      - "docs/**"

# Jobs to run
jobs:
  release:
    name: 🎉 Publish to GitHub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Dependencies
        run: npm install --no-save semantic-release @semantic-release/exec @google/semantic-release-replace-plugin @semantic-release/git

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_AUTHOR_NAME: github-actions[bot]
          GIT_AUTHOR_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
          GIT_COMMITTER_NAME: github-actions[bot]
          GIT_COMMITTER_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
        run: make sem-release
